from django.urls import path, include
from . import views

urlpatterns = [
     path('',views.main, name = 'main'),
     path('login/',views.loginPage, name = 'login'),
     path('logout/',views.logoutUser, name = 'logout'),
     path('register/',views.registerPage, name = 'register'),
     path('catalog/<str:products>/',views.catalog, name = 'catalog'),
     path('info/<str:pk>/', views.info, name = 'info'),
     path('add-to-cart/', views.addToCart, name='add-to-cart'),
     path('cart/', views.cart, name='cart'),
     path('reviews/<str:pk>', views.reviews, name='product-reviews'),
     path('post-review/<str:pk>', views.postReview, name='post-review'),
     path('delete-review/<str:prod_id>/<str:pk>', views.deleteReview, name='delete-review'),
     path('add_product/<str:product_type>', views.addProduct, name='add_product', kwargs={'allowed_types':'mouse|keyboard|headphones'}),
     path('update-product/<str:pk>', views.updateProduct, name='update-product'),
     path('delete-product/<str:pk>', views.deleteProduct, name='delete-product'),
     path('delete-image/<str:pk>/<str:pk2>', views.deleteImage, name='delete-image'), # возможно нужно будет удалить
     path('admin-panel/',views.adminPanel, name = 'admin-panel'),
     path('person-panel/',views.personPanel, name = 'person-panel'),
     path('profile/',views.profile, name = 'profile'),
     path('update-profile/',views.updateProfile, name = 'update-profile'),
     path('user-orders/',views.userOrders, name = 'user-orders'),
     path('contact-information/', views.contactInformation, name='contact-information'),
     path('change-password/', views.changePassword, name='change-password'),
     path('auth/', include('social_django.urls', namespace='social')),
     path('password-reset/',
          views.CustomPasswordResetView.as_view(),
          name='password_reset'),
     path('password-reset/done/',
          views.CustomPasswordResetDoneView.as_view(),
          name='password_reset_done'),
     path('password-reset/<uidb64>/<token>/',
         views.CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
     path('password-reset/complete/',
         views.CustomPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
     path('payment_process/', views.payment_process, name='payment_process'),
     path('payment_completed/', views.payment_completed, name='payment_completed'),
     path('payment_canceled/', views.payment_canceled, name='payment_canceled'),
]