# Generated by Django 4.2.11 on 2024-05-11 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_user_name_remove_user_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Введите корректный номер телефона, содержащий только цифры и знак '+'", regex='^\\+?[0-9]+$')]),
        ),
    ]
