# Generated by Django 4.2.11 on 2024-05-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bonus',
        ),
    ]
