# Generated by Django 4.2.11 on 2024-05-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_user_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('В обработке', 'В обработке'), ('Принят', 'Принят'), ('Отменен', 'Отменен')], default='-', max_length=20),
        ),
    ]
