# Generated by Django 4.2.11 on 2025-03-13 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_headphones_name_alter_keyboard_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphones', 'Headphones')], default='', max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2030)])),
                ('characteristics', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='headphones',
            name='date',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2030)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headphones',
            name='ruggedness',
            field=models.BooleanField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], null=True),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='wireless',
            field=models.BooleanField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], null=True),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='cable_sleeving',
            field=models.BooleanField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], null=True),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='date',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2030)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='wireless',
            field=models.BooleanField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], null=True),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='сyrillic',
            field=models.BooleanField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='backlight',
            field=models.BooleanField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='date',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2030)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mouse',
            name='wireless',
            field=models.BooleanField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
