# Generated by Django 4.2.11 on 2025-03-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_product_alter_headphones_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
    ]
