# Generated by Django 4.2.11 on 2025-03-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='shared_id',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Keyboard', 'Клавиатура'), ('Mouse', 'Мышь'), ('Headphones', 'Наушники')], default='', max_length=40),
        ),
    ]
