# Generated by Django 4.2.11 on 2025-03-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_productimage_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('keyboard', 'Клавиатура'), ('mouse', 'Мышь'), ('headphones', 'Наушники')], default='', max_length=40),
        ),
    ]
