# Generated by Django 4.2.11 on 2025-03-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='shared_id',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='shared_id',
        ),
        migrations.DeleteModel(
            name='Headphones',
        ),
        migrations.DeleteModel(
            name='Keyboard',
        ),
        migrations.DeleteModel(
            name='Mouse',
        ),
        migrations.DeleteModel(
            name='SharedID',
        ),
    ]
